kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: ocp4-auto-approve-csr
  namespace: openshift-cron-jobs
spec:
  schedule: '@hourly'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: openshift-client
              image: 'quay.io/cwawak/ocp4-auto-approve-csr:master'
              args:
                - /bin/sh
                - '-c'
                - ./startup.sh
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
